#pragma once

#include <k/types.h>

#define IRQ_DEF_HANDLER(ID) u32 irq ## ID ## Handler()

IRQ_DEF_HANDLER(0);
IRQ_DEF_HANDLER(1);
IRQ_DEF_HANDLER(2);
IRQ_DEF_HANDLER(3);
IRQ_DEF_HANDLER(4);
IRQ_DEF_HANDLER(5);
IRQ_DEF_HANDLER(6);
IRQ_DEF_HANDLER(7);
IRQ_DEF_HANDLER(8);
IRQ_DEF_HANDLER(9);
IRQ_DEF_HANDLER(10);
IRQ_DEF_HANDLER(11);
IRQ_DEF_HANDLER(12);
IRQ_DEF_HANDLER(13);
IRQ_DEF_HANDLER(14);
IRQ_DEF_HANDLER(15);
